version: "3.4"
services:
  web:
    image: ghcr.io/smartstore/smartstore-linux
    container_name: web
    ports:
      - "88:80"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - "./Tenants/:/app/App_Data/Tenants:rw"
  db:
    image: mysql
    container_name: mysql
    environment:
      #MYSQL_DATABASE: smartstore
      #MYSQL_USER: "root"
      MYSQL_PASSWORD: "Smartstore2022!"
      MYSQL_ROOT_PASSWORD: "Smartstore2022!"
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - "./mysql/:/var/lib/mysql:rw"

volumes:
  mysql:
